README.md
cogs/commands.py
exceptions.py
messages.json
utils.py

Let's try this again
Redo of #5, I read somewhere it was fine to delete the repo once it was in a PR, but I guess not.
Warns if no Applicant role exists on startup
Ignores if no Applicant role exists when using /induct
Removes Applicant from user if the role exists when using /induct
(It's safe to try to remove a role a user doesn't have)

/induct removes applicant role from user.

---

README.md
tests/utils_test.py

The tests for utils.py were failing because the program was not being called from a shell. The permissions were not granted to the test suite to run the program, so all tests failed.

Fix pytest file permissions

---

pyproject.toml
tests/utils_test.py

Don't use shell=True when opening a subprocess (https://beta.ruff.rs/docs/rules/subprocess-popen-with-shell-equals-true/)

Fix shell=True security issues & reference script by module

---

cogs/commands.py
cogs/events.py
config.py
utils.py

When unhandled exceptions are raised by a failing command, a suitable error message will be sent to the use then the error will be logged (both to stderr and the Discord webhook logging channel)

Log major error exceptions

---

cogs/strike.py

The current name of the function conflicts with the function named in `StrikeCommandCog`

Fix invalid `user_strike` function name

---

.gitignore
db/settings.py

As confirmed by [this](https://stackoverflow.com/a/808535/14403974) StackOverflow answer, the database file should not broadcast which schema is used and as such should be renamed to `core.db`.

Rename core DB file

---

main.py

Reverts CSSUoB/TeX-Bot-Py-V2#109
This intent is not required for the bot and was incorrectly added by some committee members who were being too frivolous with their pull request reviews.
I would like to personally apologise to members who may have been affected. TeXBot will never *intentionally* access your message contents.

Revert "Add the message content intent"

---

cogs/command_error.py
cogs/induct.py
cogs/make_member.py
cogs/send_get_roles_reminders.py
cogs/send_introduction_reminders.py
cogs/stats.py
cogs/strike.py
cogs/write_roles.py
config.py
example.env
messages.json
utils/tex_bot.py

Rename `TeXBot.group_name` to `TeXBot.full_group_name` & replace old `TeXBot.full_group_name` with `TeXBot.group_short_name`

Improve `GROUP_NAME` Env variable referencing & documentation

---

utils/suppress_traceback.py

This PR fixes a  bug within the `SuppressTraceback` context manager where exceptions were not handled correctly when raised & the the context manager exits.

Fix raised-exception bug in `SuppressTraceback` context manager

---

cogs/send_introduction_reminders.py

The boolean predicate checks are constants so should be uppercased and marked with [`Final`](https://docs.python.org/3/library/typing.html#typing.Final)

Improve opt-out buttons checks

---

cogs/stats.py

The internal `settings["_GROUP_SHORT_NAME"]` value may be null/`None` & the code determining the Discord server name in the description generator for the `stats` commands should handle this.

Fix bug in determining Discord server name

---

config.py

Cyclical import errors currently occur because Django's `management` command interface was imported at module scope, rather than runtime.

Fix DB setup imports at incorrect state

---

config.py

The format string for the current logging handler does not contain the actual logging message, so no message is output. This change fixes that.

Show logging messages after formatting

---

config.py
poetry.lock
pyproject.toml
tests/test_utils.py

When loaded into the runtime container, there is no git repo alongside the files. Thus an alternate solution from using the git repo is required to resolve/locate `PROJECT_ROOT`

Fix resolving `PROJECT_ROOT` without using `gitpython`

---

README.md

This will need to be changed *again* when py-cord returns to publishing their package on pypi.

Fix the shield badge query for retrieving the py-cord package version on `README.md`

---

exceptions.py
utils/generate_invite_url.py

When this PR is merged any instances running in production will need to be re-invited, in order to update their permissions. Please use this command:
```shell
docker exec {TeXBot container name} poetry run python -m utils generate_invite_url {discord_bot_application_id}
```

Fix broken check at `on_member_remove` event

---

cogs/send_get_roles_reminders.py

When retrieving audit log entries within `send_get_roles_reminders`, only `StopIteration` exception is excepted, whereas `StopAsyncIteration` should also be suppressed

Fix bug with retrieving audit log entries

---

cogs/send_get_roles_reminders.py
cogs/send_introduction_reminders.py

Puts the check to make sure the user is in the guild to be the very first check as this supersedes all others because if they're not in the server there's no point checking anything else.

Add note about why there is a seemingly superfluous check for whether the member is part of the guild

---

cogs/make_applicant.py

The `intro_channel` retrieval has been moved to just before the location where it is first used, to prevent it being retrieved if the command fails early.

Improve retrieval of `intro_channel`

---

cogs/make_member.py

I've kept the old ones in because I already have trust issues, you think I'm gonna trust the Guild to not potentially change them back?

Add new table names to the make_member cog

---

cogs/induct.py
cogs/make_applicant.py

The `ctx.typing` co-routine doesn't work the way we thought it did (as a replacement for deferral) so this adds in the proper deferral method as inductions have been timing out.

Use real defer method for long methods

---

.github/workflows/check-build-deploy.yaml
.github/workflows/prevent-migrations-deletion.yaml

If it's determined that `prevent-migration-deletion` can run fine on pushes then this check can be added back and the if statement removed from the other job. 
As it stands the build-and-publish job will never run on pushes to main

Remove `prevent-migration-deletion` job from `build-and-publish` job's `needs`

---

cogs/strike.py

Adds error handling to DM messages and allows use of webhook if failure

Implement strike message failover

---

utils/command_checks.py

The `cls._check_interaction_user_in_main_guild` and `cls._check_interaction_user_has_committee_role` have underscores at the start of their attribute names which aren't present when they are declared further up in the class so I removed them to fix the error.

Fix ignored `CommandChecks` NameError
